### ISSUE TITLE
Profile: deleting old image and saving new one

### ISSUE THREAD

**Issue by igordavydsson** [City-of-Helsinki/omahelsinki#101]
When I delete the old image and save a new one, my browser still displays the old image, since the url for the new image is exactly the same as for the old one and the browser just loads the old image from cache. 🤔 Had to hard reload the page to make the browser fetch proper file.

Maybe generate some random string for the profile image file's name, before saving it to the API? So that the browser would pull the new image correctly.

**Comment by jimppa** [comment]
Should be fixed now
