### ISSUE TITLE
History tab: pagination styling

### ISSUE THREAD

**Issue by anmipa** [City-of-Helsinki/omahelsinki#132]
Looks to me like it differs from the layouts and / or opencity.design. Not flat enough :)

http://opencity.design/development/components/pagination/

**Comment by janimattiellonen** [comment]
A newer fix is waiting for review. I found some other issues with item count selector and fixed them too,

**Comment by anmipa** [comment]
I noticed the current pagination messes the table a bit when the user goes to page 2.

Maybe because the pagination jumps a bit to the right since it adds an arrow for previous page. Not so important, but would be better if the pagination didn't jump. But as I said, this is an minor issue.
