### ISSUE TITLE
Language selection: change the order of languages to FI, SV, ENG

### ISSUE THREAD

**Issue by anmipa** [City-of-Helsinki/omahelsinki#142]
Now it is FI, ENG, SV. Make Swedish the second option and English the third.

**Comment by janimattiellonen** [comment]
Also, some of the choices have a capital letter, others don't. Maybe normalize that too.

**Comment by anmipa** [comment]
Good point. I guess I was thinking language conventions. English in capital, Finnish and Swedish not. 

I don't know 🗡

**Comment by janimattiellonen** [comment]
Ah, ok. Just looked funny. Didn't think of any such conventions.

**Comment by anmipa** [comment]
But it does look silly, you are right. 

Maybe we should just normalize: everything in capital. Even if it's wrong grammatically.

Yep, let's do that.
