### ISSUE TITLE
Login: when user has a profile, redirect to /mydata

### ISSUE THREAD

**Issue by anmipa** [City-of-Helsinki/omahelsinki#152]
Now user stays in Landing page after login. Since this is a profile-handling service, it makes sense to redirect the user always to /mydata.

**Comment by janimattiellonen** [comment]
When I log in, I'm redirected to /mydata

**Comment by janimattiellonen** [comment]
Aaaand now it doesn't anymore :)

**Comment by janimattiellonen** [comment]
The login button on the front page does not redirect to /mydata. Afaik, the content is in wagtail so the change must be done there?

**Comment by anmipa** [comment]
Assigned Igor for this. To check the Wagtail part.

**Comment by anmipa** [comment]
Assigned Tuomas.
