### ISSUE TITLE
Some photos cannot be used as a profile image

### ISSUE THREAD

**Issue by janimattiellonen** [City-of-Helsinki/omahelsinki#164]
Some photos taken with (at least) iPhone 8+ cannot be used as a profile image. 403 is given (the image return value is null)

**Comment by janimattiellonen** [comment]
Something seems to happen in the backend during image upload.

For example, this resource faield to be saved: https://profile-api.test.hel.ninja/profile-test/media/c02511fc-ddcb-11e8-be12-c2a5d7836672/profile_images/1542883622143.png

Maybe something can be found in the server logs for the url above?

**Comment by janimattiellonen** [comment]
Also, the api backend that handles saving  of the image could return a non-2xx status if the image was not successfully saved.

**Comment by tuomas777** [comment]
Will be probably fixed by https://github.com/City-of-Helsinki/open-city-profile/pull/30

**Comment by janimattiellonen** [comment]
Merg merg :)

**Comment by tuomas777** [comment]
Fixed by https://github.com/City-of-Helsinki/open-city-profile/pull/30
