### ISSUE TITLE
Add UI logic to support launch with 1 service only

### ISSUE THREAD

**Issue by anmipa** [City-of-Helsinki/omahelsinki#170]
It is possible that we launch with only one service connected to Omahelsinki.

This means that we need to refactor some components to know if there is only 1 service or several services connected to Omahelsinki.  A lot of changes can be done in text, but there are some components that need work in code.

If only 1 service, this includes:
Landing page
- front page -> hide "See all services"  or something similar
- services -> change "We have 4 services" to something else in text (not plural), or do this in some better way in code.

Mydata
- if there is only 1 service and it is connected -> hide "Not yet connected services".

There might be other changes needed.

These are just suggestions, if you come up with better solutions, would be appreciated!

**Comment by janimattiellonen** [comment]
Shouldn't we hide the "See all services" button on the landing page if there aren't more services available than what are listed on the landing page?

For example if we show 2 services and there are only 2 services then don't show the button?

**Comment by janimattiellonen** [comment]
What is "to something else in text (not plural)"? :)

**Comment by anmipa** [comment]
> What is "to something else in text (not plural)"? :)

The current text "We have X services" is a bit silly in any case :) Something like "Oma.helsinki currently works with" would be better.
