### ISSUE TITLE
Mobile UI fixes

### ISSUE THREAD

**Issue by anmipa** [City-of-Helsinki/omahelsinki#171]
Minor mobile UI fixes needed.
1) "This is the development version of Oma.helsinki"
- Close indicator (x) overlaps with text.
2) Landing page front: "Don't worry we have the answers! See help"
- Arrow too small
3) Landin page services: "Not a user?"
- Arrow too small

Screenshots in comments below.

**Comment by anmipa** [comment]
![screenshot_20181126-224206_chrome](https://user-images.githubusercontent.com/22621508/49041302-7ea2fa80-f1cd-11e8-87af-c7d347cdf630.jpg)

![screenshot_20181126-224214_chrome](https://user-images.githubusercontent.com/22621508/49041310-85317200-f1cd-11e8-906f-98198fc5f1a8.jpg)

![screenshot_20181126-224248_chrome](https://user-images.githubusercontent.com/22621508/49041314-8bbfe980-f1cd-11e8-9bc2-2b43924cfa86.jpg)

**Comment by anmipa** [comment]
Landing page, Services, Featured services: when page loads, koro-shape flashes on screen.

**Comment by janimattiellonen** [comment]
Probably because some of the contents is not available first and added after page load, which causes some flashing
