### ISSUE TITLE
Services component

### ISSUE THREAD

**Issue by jimppa** [City-of-Helsinki/omahelsinki#19]
Create a component that's used to render services.
Used on My data page to show services that user is NOT yet using.
Same component should be used to render services on wagtail Services page. A new entry point for react (`ReactDOM.render()`) is needed for this page.

**Comment by anmipa** [comment]
For MVP: services that have descriptions in Tunnistamo. At the moment 4 services.

**Comment by anmipa** [comment]
On Wagtail services page we should also show services when the user is not logged in.

This might need a new component (show all services).
