### ISSUE TITLE
Onboarding changes

### ISSUE THREAD

**Issue by jimppa** [City-of-Helsinki/omahelsinki#20]
Disable the following steps:
  - Personal information
  - Password
 
Your Interests step:
  - Use API instead of mocks for subjects, regions and decisions
  - emit the selected values to container (`Onboarding`-component)

New step that replaces Personal Information:
  - Fields for nickname and profile picture. Default image fetched from fb/g+/github/...

**Comment by anmipa** [comment]
We decided not to fetch default image from fb/g+/github.. for privacy reasons.
