### ISSUE TITLE
My data changes

### ISSUE THREAD

**Issue by jimppa** [City-of-Helsinki/omahelsinki#21]
Implement Services, currently lorem ipsum.

Profile:
  - Show first/last/email as text instead of input since they can't be changed.
  - Remove password
 
History
  - use API to fetch events

Interests:
  - should use API

**Comment by anmipa** [comment]
Looks like everything else ok, focus on interests API now.

Should include language support, API serves fi sv eng.

**Comment by anmipa** [comment]
Assigned @jimppa for the last step of this issue: Implement Services, currently lorem ipsum.
