### ISSUE TITLE
Profile: IE11 issues

### ISSUE THREAD

**Issue by anmipa** [City-of-Helsinki/omahelsinki#47]
Yes, we still use it. Yes, it has issues.

Will be tackled when time.

**Comment by anmipa** [comment]
Assigned to me for later delegation.

**Comment by jaaniles** [comment]
Fixed /mydata and /welcome pages, doesn't crash anymore. Also fixed issues with adding, setting and cropping images. Reopen or revisit when, not if, more problems arise with IE.
